package com.dnk.wallpaperlyrics

import com.google.gson.Gson
import com.google.gson.annotations.SerializedName
import java.io.File
import java.util.zip.ZipFile

/**
 * Imports lyrics from a zip archive generated by the forced alignment pipeline.
 */
class LyricsZipImporter(
    private val storage: LyricsStorage,
    private val undoDir: File
) {

    data class ImportResult(
        val importedNew: Int,
        val replaced: Int,
        val overrideActive: Int,
        val failed: Int,
        val failedTitles: List<String>
    )

    private data class Manifest(
        val format: Int? = null,
        val created: String? = null,
        val source: String? = null,
        val entries: List<ManifestEntry>? = null
    )

    private data class ManifestEntry(
        val file: String? = null,
        val title: String? = null,
        val artist: String? = null,
        @SerializedName("duration_ms")
        val duration_ms: Long? = null,
        @SerializedName("spotify_id")
        val spotify_id: String? = null
    )

    private val gson = Gson()

    fun hasUndo(): Boolean {
        return undoDir.exists() && (undoDir.listFiles()?.isNotEmpty() == true)
    }

    fun importZip(
        zipFile: File,
        onProgress: ((done: Int, total: Int) -> Unit)? = null
    ): ImportResult {
        val zip = ZipFile(zipFile)
        try {
            val manifestEntry = zip.getEntry("manifest.json")
                ?: throw IllegalArgumentException("Missing manifest.json in zip archive")

            val manifestJson = zip.getInputStream(manifestEntry).bufferedReader(Charsets.UTF_8).use {
                it.readText()
            }

            val manifest = gson.fromJson(manifestJson, Manifest::class.java)
                ?: throw IllegalArgumentException("Could not parse manifest.json")

            if (manifest.format != 1) {
                throw IllegalArgumentException("Unsupported manifest format: ${manifest.format} (expected 1)")
            }

            val entries = manifest.entries ?: emptyList()
            val total = entries.size

            if (undoDir.exists()) {
                undoDir.deleteRecursively()
            }
            undoDir.mkdirs()

            val createdKeys = mutableSetOf<String>()
            val failedTitles = mutableListOf<String>()
            var importedNew = 0
            var replaced = 0
            var overrideActive = 0
            var failed = 0

            try {
                for ((index, entry) in entries.withIndex()) {
                    val title = entry.title
                    val artist = entry.artist ?: ""
                    val filePath = entry.file

                    if (title.isNullOrBlank() || filePath.isNullOrEmpty()) {
                        failed++
                        failedTitles.add(title ?: "Unknown")
                        onProgress?.invoke(index + 1, total)
                        continue
                    }

                    val lrcZipEntry = zip.getEntry(filePath)
                    if (lrcZipEntry == null) {
                        failed++
                        failedTitles.add(title)
                        onProgress?.invoke(index + 1, total)
                        continue
                    }

                    val lrcText = try {
                        zip.getInputStream(lrcZipEntry).bufferedReader(Charsets.UTF_8).use {
                            it.readText()
                        }
                    } catch (e: Exception) {
                        failed++
                        failedTitles.add(title)
                        onProgress?.invoke(index + 1, total)
                        continue
                    }

                    val lines = LyricsManager.parseLrcText(
                        lrcText = lrcText,
                        durationMs = entry.duration_ms,
                        isAuthoritative = false,
                        trustWordEnds = true
                    )

                    if (lines.isNullOrEmpty()) {
                        failed++
                        failedTitles.add(title)
                        onProgress?.invoke(index + 1, total)
                        continue
                    }

                    val key = storage.cacheKey(title, artist)
                    val cacheFile = storage.getCacheFile(title, artist)
                    val existed = cacheFile.exists()
                    val hasOverride = storage.getOverrideFile(title, artist).exists()

                    if (existed) {
                        val backupFile = File(undoDir, "$key.json")
                        if (!backupFile.exists()) {
                            cacheFile.copyTo(backupFile, overwrite = true)
                        }
                    } else {
                        createdKeys.add(key)
                    }

                    if (!storage.fetchedDir.exists()) {
                        storage.fetchedDir.mkdirs()
                    }
                    cacheFile.writeText(gson.toJson(lines))
                    cacheFile.setLastModified(System.currentTimeMillis())

                    val missFile = storage.getMissFile(title, artist)
                    if (missFile.exists()) {
                        missFile.delete()
                    }

                    if (hasOverride) {
                        overrideActive++
                    } else if (existed) {
                        replaced++
                    } else {
                        importedNew++
                    }

                    onProgress?.invoke(index + 1, total)
                }
            } finally {
                // Persist created keys so undo can clean up even after partial import failure
                if (undoDir.exists()) {
                    try {
                        val createdKeysFile = File(undoDir, "created_keys.json")
                        createdKeysFile.writeText(gson.toJson(createdKeys.toList()))
                    } catch (ignored: Exception) {}
                }
            }

            storage.evictOldEntries()

            return ImportResult(
                importedNew = importedNew,
                replaced = replaced,
                overrideActive = overrideActive,
                failed = failed,
                failedTitles = failedTitles
            )
        } finally {
            try {
                zip.close()
            } catch (ignored: Exception) {}
        }
    }

    fun undoLastImport(): Boolean {
        if (!undoDir.exists() || !undoDir.isDirectory) {
            return false
        }
        val files = undoDir.listFiles() ?: return false
        if (files.isEmpty()) {
            return false
        }

        val createdKeysFile = File(undoDir, "created_keys.json")
        if (createdKeysFile.exists()) {
            try {
                val keys = gson.fromJson(createdKeysFile.readText(), Array<String>::class.java)
                if (keys != null) {
                    for (key in keys) {
                        val cacheFile = File(storage.fetchedDir, "$key.json")
                        if (cacheFile.exists()) {
                            cacheFile.delete()
                        }
                    }
                }
            } catch (ignored: Exception) {}
        }

        for (file in files) {
            if (file.name == "created_keys.json") continue
            if (file.name.endsWith(".json")) {
                val targetFile = File(storage.fetchedDir, file.name)
                file.copyTo(targetFile, overwrite = true)
            }
        }

        undoDir.deleteRecursively()
        return true
    }
}
